// Generated-adjacent, hand-maintained: the prompt registry, moved out of
// server.h so that editing a prompt does not recompile every translation
// unit that merely uses the server.
#include "server.h"

auto PostgresMCPServer::prompt_defs() -> const std::vector<PromptDef>& {
    static const std::vector<PromptDef> v = {
      {"diagnose-slow-query",
       "Trace a slow statement from pg_stat_statements to a plan and a fix.",
       {{"query_id", "queryid from statementStats; omit to start from the worst offender", false},
        {"min_duration_s", "ignore statements faster than this mean duration", false}},
       [](const json& a) -> std::string {
         const std::string qid = arg_or(a, "query_id", "");
         const std::string mind = arg_or(a, "min_duration_s", "");
         std::string s =
           "Diagnose a slow statement on this PostgreSQL server.\n\n"
           "0. Call checkPrivileges first. statementStats hides the query text "
           "of other roles without stats access, explainQuery needs SELECT on "
           "the tables referenced, and tableBloat needs a grant of its own -- "
           "a plan built on tools that will not answer wastes the incident.\n"
           "1. Call statementStats to rank statements by total execution time. "
           "Read info.dealloc first: if it is non-zero the extension has been "
           "evicting entries, so the list is the slowest of what survived, not "
           "the slowest overall -- say so before drawing conclusions.\n";
         if (!qid.empty())
           s += "2. The statement of interest is query_id " + qid +
                ". Call explainQuery with that queryid.\n";
         else
           s += "2. Pick the statement with the largest total_exec_time"
                + (mind.empty() ? std::string()
                                : " whose mean duration is at least " + mind + "s")
                + " and call explainQuery with its query_id.\n";
         s +=
           "3. Read the plan for the usual causes in this order: a sequential "
           "scan on a large table, an estimate that is orders of magnitude off "
           "the actual row count, a sort or hash that spilled to disk, and a "
           "nested loop driven by a bad estimate.\n"
           "   The spill you can confirm without the plan: statementStats already "
           "returned temp_blks_read and temp_blks_written for this statement in "
           "step 1, and a non-zero write count is the sort or hash going to disk, "
           "every time it ran rather than the once EXPLAIN ANALYZE watched. Use "
           "the plan to find which node, and the counter to know it is typical.\n"
           "   Before concluding anything from a spill, read the plan's Settings "
           "block. It lists what differs from the built-in default in THIS "
           "session, and the statement does not run in this session. work_mem "
           "decides whether a sort or hash spills at all, so a spill visible "
           "here and absent in production -- or the reverse -- is a difference "
           "in environment rather than in the statement. hostCapacity.overrides "
           "carries the per-role and per-database values pg_settings cannot "
           "show; where the executing role has its own work_mem, say that this "
           "plan is not the plan production gets before ranking any cause.\n"
           "4. If the estimates are wrong, call tableStats on the tables "
           "involved and compare n_mod_since_analyze against last_analyze and "
           "last_autoanalyze -- stale statistics explain more bad plans than "
           "missing indexes do, and those two timestamps also say whether "
           "anything is analyzing the table at all or somebody is doing it by "
           "hand.\n"
           "   If the statistics are current and the estimate is still wrong, the "
           "column is probably skewed rather than stale, and that is a different "
           "fix. most_common_vals and histogram_bounds in the same payload are "
           "the evidence: a predicate on a value in the MCV list is estimated "
           "from its recorded frequency, while one outside it is estimated from "
           "the histogram, and a planner that is right for the first and wrong "
           "for the second is describing skew rather than staleness. Call "
           "columnHistogram on that column when the shape of the distribution is "
           "what you need, and consider a higher statistics target -- it reports "
           "the one in effect -- or extended statistics where two columns are "
           "correlated.\n"
           "5. If the plan shows a sequential scan where a usable index exists, "
           "or an index scan fetching far more heap pages than it returns rows, "
           "suspect bloat rather than the plan. tableBloat measures dead space "
           "in the table, indexBloat in one index; both cost a scan, so name "
           "the object rather than sweeping the schema.\n"
           "6. If bloat is confirmed, the fix is usually vacuum reaching the "
           "table more often rather than a REINDEX. Read n_dead_tup and the "
           "last vacuum times from tableStats and the per-table autovacuum "
           "settings from tableDetails.reloptions, and follow "
           "bloat-and-vacuum-review before changing anything cluster-wide -- "
           "an unconsumed replication slot makes every autovacuum setting "
           "irrelevant, and that prompt checks for one.\n"
           "7. Before proposing an index, call duplicateIndexes to check that "
           "one does not already exist, and tableDetails to see what is there. "
           "If the change is DDL, follow plan-schema-change: an index that is "
           "correct and an index that is safe to create on a live server are "
           "different questions.\n"
           "8. Decide what kind of fix this is before writing one, and say "
           "which. Either the statement asks for something the planner cannot "
           "use -- a predicate that is not sargable, a function or a cast over "
           "an indexed column, NOT IN against a nullable subquery, OFFSET deep "
           "into a large result -- and the fix is a rewrite. Or the planner was "
           "misinformed, and the fix is statistics: an ANALYZE, a higher "
           "statistics target, or extended statistics for correlated columns -- "
           "and before proposing those, call listExtendedStatistics, because a "
           "statistics object that already exists and is not being used is a "
           "different problem from one that was never created. Read `built` "
           "rather than mere presence: an object that has never been ANALYZEd "
           "has a catalog row, no data and no effect on any plan, so it reads "
           "as a fix already tried and is really one never finished -- and "
           "there the answer is ANALYZE, not another CREATE STATISTICS. "
           "Or the plan is right but under-resourced, and the fix is "
           "configuration, such as work_mem for a node that spilled. Or the "
           "statement is already well formed and nothing supports the access "
           "path it needs -- and only then is the fix DDL.\n"
           "   Prefer them in that order, because that is the order of what "
           "they cost. An ANALYZE is free and instant. A rewrite costs a deploy "
           "and nothing in the database. Configuration changes the behaviour of "
           "every other query too. An index is a write cost paid by every "
           "INSERT and UPDATE for as long as it exists, to buy speed for one "
           "read pattern. Say why the cheaper options were rejected rather than "
           "passing over them.\n"           "9. Verify what can be verified. A rewrite can be checked here and "
           "now: call explainQuery on the rewritten statement and show that the "
           "plan actually changed, and how. An index is checkable too "
           "wherever hypopg is installed: call evaluateIndex with the CREATE "
           "INDEX statement and report whether the planner actually took it, "
           "because a proposed index the planner ignores is the common case "
           "and a cost figure alone hides it. checkPrivileges says whether "
           "hypopg is there; where it is not, an index is a prediction and has "
           "to be presented as one rather than as a result. Either way hand "
           "the creation to plan-schema-change: whether an index is correct "
           "and whether it is safe to build on this server are different "
           "questions, and evaluateIndex answers only the first.";
         return s;
       }},

      {"triage-lock-contention",
       "Find what is blocking what, and who to look at first.",
       {{"connection", "connection to investigate; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Triage lock contention" + on + ".\n\n"
           "0. Call checkPrivileges. Without stats access, currentActivity hides "
           "the query text of backends belonging to other roles, which is most "
           "of what this investigation reads.\n\n"
           "Read before you write. Do not kill anything, and do not recommend "
           "killing anything until the last step.\n\n"
           "This is for a wait that is still happening. If what you have is a "
           "deadlock the server already detected and logged, the sessions in it "
           "are gone and nothing below will find them -- use diagnose-deadlock, "
           "which reconstructs it from the log and the schema instead.\n\n"
           "1. Call currentLocks. The rows carry a chain_depth: 0 is the "
           "backend asked about, and the largest depth is the backend at the "
           "root of the wait chain. That is the one to look at first.\n"
           "   Read mode and lock_type on the same rows before going further, "
           "because they decide what kind of problem this is. An "
           "AccessExclusiveLock at the root is DDL or a VACUUM FULL and everything "
           "behind it is stopped dead; a RowExclusiveLock is ordinary DML and the "
           "queue is moving, just slowly. granted separates what is held from what "
           "is being waited on, and wait_start says how long the queue has been "
           "stuck -- which is not the same number as how long the blocker has been "
           "running, and is the one that says how much damage is already done.\n"
           "2. Call currentActivity for the pids in the chain. For each, read "
           "state, wait_event_type, query and how long the transaction has "
           "been open.\n"
           "   Check leader_pid before deciding what any pid is. A parallel worker "
           "carries its leader's pid there, and it is the leader that holds the "
           "transaction -- terminating a worker achieves nothing and the leader "
           "simply starts another.\n"
           "   Read backend_xmin on the root as well. A backend holding an xmin "
           "horizon is not only blocking this chain: it stops vacuum removing dead "
           "tuples anywhere in the cluster, so a long idle transaction here is "
           "also the bloat somebody else is investigating. If it is set and old, "
           "say so, and hand the second half to bloat-and-vacuum-review.\n"
           "3. An idle in transaction backend at the root is the usual answer, "
           "and the fix is in the application that left it open, not in the "
           "database -- so name the application rather than the pid. "
           "currentActivity carries application_name, user and client_addr for "
           "exactly this: a pid is gone by the time anyone acts on the report, "
           "while a connection pool, a deploy or a host is something an operator "
           "can go and fix. query_id links the statement to statementStats, which "
           "says whether this is a recurring pattern or one bad session.\n"
           "4. Report the chain root, what it is doing, how long it has held "
           "the lock, and what is queued behind it. Only then discuss whether "
           "terminating it is safe, and say what would be lost.";
       }},

      {"diagnose-deadlock",
       "Work out why a logged deadlock happened, from the log entry plus the schema.",
       {{"deadlock_log", "the deadlock report from the server log: the ERROR line, "
                         "the DETAIL block naming each process, and the statements", true},
        {"connection", "connection the deadlock happened on; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string log = arg_or(a, "deadlock_log", "");
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Investigate this deadlock" + on + ".\n\n"
           "The log:\n" + log + "\n\n"
           "Start from what is no longer true. The deadlock is over: PostgreSQL "
           "detected the cycle, killed one transaction and released the other. "
           "The pids in that log do not exist any more, so currentActivity and "
           "currentLocks describe a server that has already moved on, and "
           "triage-lock-contention -- which is about a wait chain you can still "
           "see -- does not apply. Everything below reconstructs the deadlock "
           "from the log and the schema. Reach for the live tools only in step "
           "6, and only if it is still recurring.\n\n"
           "0. Call checkPrivileges. explainQuery and statementStats are the two "
           "this needs and the two a restricted role loses; without them say so "
           "rather than guessing at plans.\n"
           "1. Read the log before touching the database, because it already "
           "settles more than it is usually given credit for. For each process "
           "extract three things: the statement it was running, the lock it "
           "waited for, and the lock it held. The kind of lock names the shape "
           "before you look at anything:\n"
           "   - 'ShareLock on transaction N' means it was waiting for a row "
           "another transaction had written and not yet committed. This is the "
           "common case and it is a row-ordering problem.\n"
           "   - 'ExclusiveLock on tuple (x,y)' is the queue for one specific "
           "row: several transactions want the same row and are lined up.\n"
           "   - a relation-level lock, especially AccessExclusiveLock, means "
           "DDL or an explicit LOCK TABLE was in the cycle, not ordinary DML.\n"
           "2. The statement text is not the lock footprint, and assuming it is "
           "is why deadlocks between statements that name different tables look "
           "impossible. For every table named, call tableDetails and read:\n"
           "   - foreign keys in BOTH directions. Writing a row that references "
           "a parent takes a lock on the parent row too, so a statement that "
           "names only the child touches the parent, and two children pointing "
           "at two parents in opposite orders deadlock without ever naming the "
           "same table.\n"
           "   - triggers. A trigger runs statements the log never shows, "
           "against tables the statement never names.\n"
           "   - unique indexes. Two inserts of the same key do not conflict on "
           "a row that exists; the second waits on the first transaction to end.\n"
           "   If a statement calls a function or procedure, call "
           "functionDetails and read the body: the transaction is the whole "
           "body, and the ordering that matters is the order the body takes.\n"
           "3. Now reconstruct the acquisition ORDER for each transaction, "
           "because that is the only thing that ever causes a deadlock. Two "
           "transactions took the same locks in different orders; nothing else "
           "produces a cycle. Write the order out per transaction, including "
           "the locks step 2 found that the statements do not mention, and say "
           "where the two orders cross.\n"
           "4. Call explainQuery for each statement. The plan decides the order "
           "rows are locked, so two UPDATEs with identical WHERE clauses lock "
           "in different orders when one uses an index scan and the other a "
           "sequential scan -- and a plan flip is enough to start a deadlock "
           "that was not happening last week. Where the statement came from "
           "pg_stat_statements, recover it with explainQuery by queryid first. "
           "Do not use analyze: it executes, and this is a post mortem.\n"
           "5. Classify it, and say which reading decided it: rows taken in "
           "different orders, a foreign key pulling in a parent, a trigger "
           "widening the footprint, contention on one unique key, or explicit "
           "locking in inconsistent order.\n"
           "6. Only now ask whether it is still happening, and escalate in three "
           "stages. Each one is licensed by the one before it, and in each the "
           "fact that the statement APPEARS is itself the finding, before any "
           "counter is read.\n"
           "   a. Look for it in statementStats. pg_stat_statements evicts "
           "under pressure, discarding the least-used entries first, so a "
           "statement still present in a cluster that is evicting has proved it "
           "runs often enough to survive -- and a deadlock needs concurrency, so "
           "that is the first thing worth establishing. Read info.dealloc to "
           "know whether eviction is happening at all, because it decides what "
           "presence means. Then calls and mean_exec_time say how much overlap "
           "there is between two runs.\n"
           "      Not finding it settles nothing. It may have been evicted, the "
           "counters may have been reset, or the extension may not be installed. "
           "Say which of those you ruled out rather than reporting it as rare. "
           "Match on the normalised text: the log holds one execution, "
           "pg_stat_statements holds the shape with constants replaced.\n"
           "   b. Look for it in currentActivity. If it is there, it is running "
           "right now, which turns a post mortem into something observable -- "
           "you can watch the next occurrence instead of inferring the last one. "
           "Read state and how long each transaction has been open: a statement "
           "that finishes in milliseconds cannot hold a lock long enough to "
           "deadlock with anything, so an open transaction sitting on it is the "
           "condition that makes the cycle possible.\n"
           "   c. If it is live and slow, call currentLocks. A deadlock is a "
           "wait chain that closed into a loop, so the chains forming now are "
           "the near-miss version of the one that closed -- the same edges, "
           "caught before the last one joined up. If you find a real chain, hand "
           "off to triage-lock-contention, which is built for a wait you can "
           "still see; come back here with what it found about the root.\n"
           "   Whatever the stage, serverSettings gives deadlock_timeout, and "
           "log_lock_waits being off means every long wait that did not quite "
           "close into a cycle went unlogged -- so the log you are reading is "
           "the only one of these events you were ever going to see.\n"
           "7. Rank the fixes, and rank them in this order: make the "
           "acquisition order consistent between the two paths, then shrink the "
           "lock footprint, then shorten the transaction so the window is "
           "smaller. Be explicit that deadlock_timeout is not a fix -- it "
           "changes when the cycle is detected, never whether it forms -- and "
           "that max_locks_per_transaction has nothing to do with this. "
           "Retrying on SQLSTATE 40P01 belongs in the application and is a "
           "mitigation, not a diagnosis: say so plainly if you recommend it, "
           "because a retry loop over an ordering bug hides it rather than "
           "fixing it.\n"
           "8. If the fix is DDL -- an index to change a plan, a constraint to "
           "drop, a trigger to rewrite -- hand it to plan-schema-change rather "
           "than proposing the statement here. What is safe to apply depends on "
           "the size and traffic of the table, which that prompt measures.";
       }},

      {"triage-active-sessions",
       "Find why a server is running more sessions at once than it has CPUs to run them on.",
       {{"connection", "connection to investigate; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Work out why this server has so many sessions running at once" + on +
           ".\n\n"
           "Two things have to be established before any of it means anything, "
           "and both are routinely assumed instead.\n\n"
           "First, ACTIVE IS NOT ON-CPU. pg_stat_activity calls a backend active "
           "while it is executing a statement, and a backend waiting on a lock, "
           "on a disk read, or on a parallel sibling is executing a statement. A "
           "server with fifty active sessions where forty-five are waiting on "
           "locks is not short of CPU; it has one blocker and a queue. Only "
           "backends with no wait event are actually competing for CPU, and that "
           "is the number to compare against the core count.\n\n"
           "Second, HIGH CONCURRENCY IS USUALLY A SYMPTOM. The number of "
           "sessions in flight is the arrival rate multiplied by how long each "
           "one takes, so it rises when statements get slower even though "
           "nothing about the load changed. Treating that as a capacity problem "
           "-- more cores, a bigger pool -- treats the symptom and leaves the "
           "cause. Establish which of the two moved before proposing anything.\n\n"
           "0. Call checkPrivileges. Without stats access currentActivity hides "
           "the query text of other roles, which is most of what this reads, and "
           "statementStats hides most of its rows.\n"
           "1. Call hostCapacity for the core count. If it reports host vCPUs "
           "unknown, stop with a partial answer and say so: PostgreSQL cannot "
           "see the machine it runs on and the number has to be declared per "
           "connection. Everything below is a comparison against it, so guessing "
           "it invents the conclusion.\n"
           "2. Call currentActivity and count properly, because the raw number "
           "of active rows is not the concurrency.\n"
           "   - Keep only client backends. Autovacuum workers, the walsender, "
           "the checkpointer and background workers all appear here and none of "
           "them is user concurrency, though they do compete for the same "
           "cores -- count them separately rather than dropping them.\n"
           "   - Collapse parallel workers into their leaders using leader_pid. "
           "One query with four workers is five rows and one unit of user "
           "concurrency. Report both numbers, because the gap between them is "
           "how much of the load is parallelism rather than clients, and "
           "max_parallel_workers_per_gather above 1 means a single statement can "
           "oversubscribe the machine by itself.\n"
           "   - Split what remains by wait_event_type, and read "
           "wait_event_description where it is unfamiliar rather than guessing "
           "from the name.\n"
           "3. The split is the diagnosis, and it decides which investigation "
           "this actually is. Compare ONLY the no-wait group against the core "
           "count from step 1.\n"
           "   - No wait event: on CPU. If this is at or above the core count "
           "the server is genuinely CPU-bound and step 4 is the question. If it "
           "is well below, the server is not CPU-bound whatever the active total "
           "says, and the dominant wait below is the real subject.\n"
           "   - Lock: they are queued behind something, not working. Hand off "
           "to triage-lock-contention, which follows the chain to its root. A "
           "single blocker can make a server look saturated.\n"
           "   - IO: reading from disk rather than from cache. That is "
           "buffer-cache-review, and ioStats separates real pressure from a "
           "large sequential scan recycling its own ring buffer on purpose.\n"
           "   - LWLock: contention inside PostgreSQL rather than on user data, "
           "commonly around WAL or buffer mapping. checkpointStats and ioStats "
           "are where that shows, and it usually means the write path rather "
           "than the query.\n"
           "   - IPC: frequently parallel workers waiting on each other, which "
           "points back at the parallelism settings rather than at the "
           "statements.\n"
           "   - Client: waiting on the application to send or read. The "
           "database is not the bottleneck; something on the other side is slow, "
           "or a transaction is being held open across application work.\n"
           "4. Only if the no-wait group really is at the core count: find out "
           "which of the two terms moved, because they need opposite fixes. Call "
           "statementStats.\n"
           "   - More statements arriving, with mean_exec_time roughly where it "
           "was, is genuine growth. That is a capacity answer: a connection "
           "pooler to bound the concurrency, or more cores.\n"
           "   - The same statements taking longer than they did is a "
           "regression, and the concurrency is its consequence rather than its "
           "cause. Take the worst offender to diagnose-slow-query. A plan that "
           "flipped, statistics that went stale, a table that bloated or a "
           "working set that outgrew the cache will all show here as a load "
           "problem and none of them is one.\n"
           "   - Say which it is and what the reading was. If you cannot tell "
           "because there is no earlier figure to compare against, say that too, "
           "and note that mean_exec_time needs a before-value or a reset to mean "
           "anything.\n"
           "5. Read the duration spread from query_duration_s and "
           "xact_duration_s, because an average hides the shape. Many short "
           "statements and a few very long ones are different problems: the "
           "second is not concurrency at all, and a long-running transaction "
           "also holds back the xmin horizon, which makes it "
           "bloat-and-vacuum-review's problem simultaneously. Name the "
           "applications behind them using application_name and client_addr, "
           "since a pid is gone by the time anyone acts on the report and a "
           "connection pool or a deploy is something an operator can go and "
           "change.\n"
           "6. Check whether the pool is the problem rather than the workload. "
           "databaseStats gives numbackends against max_connections, and the "
           "session counters say whether connections are churning: sizing "
           "anything against a backend count that is high because sessions keep "
           "dying is sizing for the symptom. Without a pooler in front, every "
           "burst opens real backends and each one is a work_mem allocation "
           "waiting to happen -- capacity-check does that arithmetic.\n"
           "7. Account for the work nobody asked for. progressStats shows a "
           "VACUUM, CREATE INDEX or CLUSTER in flight, any of which takes "
           "parallel workers and I/O from everything else; wraparoundStatus "
           "shows an antiwraparound autovacuum, which will not yield and cannot "
           "be postponed, and which explains a server that is busy with no "
           "corresponding user load.\n"
           "8. Report the count that matters -- backends genuinely on CPU "
           "against cores -- not the active total, and say what the rest were "
           "waiting on. Then the cause, then the fix, ranked. Be explicit that a "
           "connection pooler bounds the damage rather than repairing it: it "
           "stops an overloaded server from getting worse, and it makes no "
           "statement faster.";
       }},

      {"bloat-and-vacuum-review",
       "Decide whether bloat is real, and whether autovacuum is keeping up.",
       {{"schema", "schema to review; defaults to public", false}},
       [](const json& a) -> std::string {
         const std::string sch = arg_or(a, "schema", "public");
         return
           "Review bloat and autovacuum health for schema " + sch + ".\n\n"
           "0. Call checkPrivileges. tableBloat and indexBloat are denied outright "
           "to a role without the scanning grant, and tableStats returns null "
           "statistics rather than an error when it cannot read a column -- "
           "which looks exactly like a table nobody has analyzed.\n"
           "1a. Call listPartitions for " + sch + " first. Autovacuum runs per "
           "PARTITION, so a partitioned parent has no vacuum state of its own: "
           "its n_dead_tup is always zero and ranking parents finds nothing "
           "while one child falls behind. Where a parent exists, take its "
           "partitions from partitionDetails and rank those instead. Read "
           "default_rows while you are there -- rows in a DEFAULT partition "
           "matched no bound, which is a missing partition that has not failed "
           "loudly yet, and for a RANGE parent the highest upper bound against "
           "now() says whether the next period's partition exists at all.\n"
           "1. Call listTableStats for " + sch + ". Rank by n_dead_tup and read "
           "last_vacuum and last_autovacuum beside it: a large dead-tuple count on "
           "a table vacuumed minutes ago is a busy table, not a neglected one.\n"
           "   Read those two apart, because together they answer the question "
           "this review is actually for. A recent last_autovacuum means autovacuum "
           "is reaching the table and the settings are working. A recent "
           "last_vacuum beside a null or ancient last_autovacuum means the "
           "opposite: somebody is keeping this table alive by hand, autovacuum is "
           "not doing it, and the cron job is hiding the finding rather than being "
           "it. Both look identical if you only ask when the table was last "
           "vacuumed. last_analyze and last_autoanalyze divide the same way.\n"
           "   Ranking by dead tuples alone misses the table most likely to hurt "
           "you, because an insert-only table never accumulates any. Read "
           "n_ins_since_vacuum as a second ranking: a large value beside an old "
           "last_vacuum is a table autovacuum reaches only through the insert "
           "threshold, and one that is never vacuumed is also never frozen, which "
           "makes it step 3's problem rather than this step's.\n"
           "   Where the server reports it (PostgreSQL 16 and later), "
           "n_tup_newpage_upd against the update count says how often an update "
           "could not stay on its page. That is a cause rather than a symptom: it "
           "means HOT is failing, either because fillfactor leaves no room or "
           "because an index covers a column the workload keeps changing, and no "
           "amount of vacuuming fixes either.\n"
           "2. Call replicationSlots before concluding anything. An inactive "
           "or lagging slot holds back the xmin horizon, which stops vacuum "
           "from removing dead tuples cluster-wide -- and no amount of "
           "autovacuum tuning fixes it. This is the single most common wrong "
           "diagnosis in this area.\n"
           "   Then find out whether the slot will ever advance, because that "
           "decides whether to wait or to drop it. For a logical slot the "
           "consumer is a subscriber on another server: call subscriptionStats "
           "on that connection. A subscriber with a climbing apply_error_count "
           "or a table still copying is stuck but alive, and fixing it releases "
           "the horizon; one that reports nothing at all is gone, and the slot "
           "is abandoned. Those two look identical from this side.\n"
           "   There is a third state that looks like abandonment and is not. "
           "Call listSubscriptions there too and read enabled beside "
           "disable_on_error. A subscription created with disable_on_error "
           "turns ITSELF off the first time apply fails, so what you see is an "
           "inactive slot, a disabled subscription, and WAL piling up behind a "
           "consumer that is neither broken nor gone -- it is waiting, exactly "
           "as configured. The fix is the apply error plus ALTER SUBSCRIPTION "
           "ENABLE, and dropping the slot here would destroy a subscriber that "
           "was one command from resuming. enabled false with disable_on_error "
           "false is the opposite: somebody disabled it by hand, and the "
           "question is who and whether they meant to leave it.\n"
           "3. Call wraparoundStatus. If any database or table is approaching "
           "autovacuum_freeze_max_age, that outranks ordinary bloat.\n"
           "   If a vacuum is running now, call progressStats before concluding "
           "that autovacuum is too slow. On PostgreSQL 18 and newer it reports "
           "delay_time_ms and delay_percent: the time that vacuum has spent "
           "ASLEEP on the cost-based delay. A vacuum that is mostly sleeping is "
           "being throttled by vacuum_cost_delay and vacuum_cost_limit, and it "
           "is indistinguishable in blocks-per-second from one on a slow disk. "
           "The two have opposite fixes -- raise the cost limit, or buy I/O -- "
           "and nothing else here tells them apart.\n"
           "4. For the worst few tables, call tableBloat to measure rather than "
           "estimate. Leave exact at its default first; the approximation is "
           "usually enough to rank them.\n"
           "5. For an index that looks redundant, duplicateIndexes says it is "
           "covered and idx_scan says nobody used it SINCE THE COUNTERS WERE "
           "RESET -- read counters_since before reading idx_scan at all. "
           "pg_stat_reset() zeroes idx_scan with everything else, so a zero on "
           "a database reset last week is an index unused for a week, which is "
           "what a month-end report, a quarterly job or a failover path looks "
           "like too. Where the window is short, idx_scan = 0 is not evidence "
           "and the honest answer is to say so and wait rather than to drop a "
           "large index on it. Note also that counters_since is a lower bound: "
           "pg_stat_reset_single_table_counters() zeroes one relation without "
           "moving it. And even a genuine zero does not prove the planner would "
           "not miss the index. Where hypopg is "
           "installed, evaluateIndex with 'hide' plans the query without the "
           "index and settles it. Dropping an index is easy; rebuilding one on "
           "a large table is not.\n"
           "6. Only where bloat is confirmed, look at per-table storage "
           "parameters via tableDetails.reloptions and propose changes. Say which "
           "reading justifies each one. The autovacuum thresholds are the usual "
           "answer for a table that is vacuumed too rarely; fillfactor is the "
           "answer for one where n_tup_newpage_upd showed HOT failing, and it "
           "treats the cause rather than the residue.";
       }},

      {"triage-disk-space",
       "Find what is filling the disk, and what can safely be freed right now.",
       {{"connection", "connection to investigate; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Find what is consuming disk" + on + " and what can be freed.\n\n"
           "Call diskUsage first. It answers this from SQL alone -- WAL size and "
           "file count, the archive status backlog, temporary files on disk now, "
           "the log directory, and sizes per tablespace and per database across "
           "the whole cluster -- so no shell on the server is needed for any of "
           "what follows.\n"
           "   One thing it cannot report, because PostgreSQL exposes no "
           "function for it: how much room is left. Sizes here are what "
           "PostgreSQL accounts for, not the volume, and anything outside "
           "PostgreSQL on the same device is invisible. Ask the operator for df "
           "if the headroom matters to the decision; everything else below is "
           "answerable without it.\n"
           "   Read tablespaces before anything else. A tablespace sits on "
           "whatever volume it was created on and carries its location, so the "
           "database that is growing and the disk that is full need not be the "
           "same device -- and the log directory is frequently a third one. "
           "Establish which volume the alert is about before ranking anything on "
           "it.\n\n"
           "Four things consume space and they need different fixes, so identify "
           "which before proposing anything. They are in this order because it "
           "is the order of how fast each can be undone, which is what matters "
           "at three in the morning.\n\n"
           "0. Call checkPrivileges. Without stats access replicationSlots and "
           "currentActivity are degraded, and those are the first two steps.\n"
           "1. WAL, which is the most common answer and the most recoverable. "
           "diskUsage.wal is what is actually on disk; replicationSlots says "
           "who is pinning it. Read retained_wal_bytes and wal_status per "
           "slot. An inactive slot pins WAL indefinitely and nothing reclaims it "
           "while the slot exists. wal_status says how far gone it is, and read "
           "it in the direction the server means it:\n"
           "     reserved   - the WAL this slot needs is within max_wal_size.\n"
           "     extended   - past max_wal_size, but still retained, EITHER by "
           "this slot or by wal_keep_size. Check the setting before blaming the "
           "slot.\n"
           "     unreserved - the slot NO LONGER retains what it needs; some of "
           "that WAL is due to be removed at the next checkpoint. This is the "
           "server choosing the disk over the consumer, and it happens when "
           "max_slot_wal_keep_size is set. For a disk-space page it is good "
           "news -- the space is about to come back on its own -- and bad news "
           "for whatever was reading the slot. It can still return to reserved "
           "or extended if the consumer catches up in time.\n"
           "     lost       - the WAL is already gone; the slot is unusable and "
           "its consumer cannot resume whatever you do next.\n"
           "   Do not read unreserved as 'this slot is what is holding the "
           "disk'. It is the opposite, and acting on it as though the slot were "
           "still pinning space wastes the one checkpoint of warning it gives.\n"
           "   Then get the budget, and read it rather than deriving it: "
           "safe_wal_size is how many bytes can still be written before this "
           "slot is in danger of becoming lost, which is exactly the "
           "'how long have I got' figure. It is null when max_slot_wal_keep_size "
           "is -1, and that null is itself the finding -- nothing bounds this, "
           "and the slot will take the disk down before PostgreSQL intervenes. "
           "Where it is set, PostgreSQL invalidates the slot rather than fill "
           "the disk, trading a broken replica for a live primary.\n"
           "   Before concluding it is a slot, read diskUsage.archive_status. A "
           "failing archive_command retains every segment it has not archived, "
           "and a climbing .ready count is exactly that -- indistinguishable "
           "from an abandoned slot by the WAL size alone, and a completely "
           "different fix. pg_stat_archiver carries failed_count and "
           "last_failed_time if you need the reason; this server does not read "
           "it, but the backlog is enough to tell which of the two you have.\n"
           "2. Temporary files, which are the fastest to free and the easiest to "
           "miss. diskUsage.temp_files is what is on disk at this moment, while "
           "databaseStats temp_files and temp_bytes are the running totals since "
           "the counters were reset -- the first says whether it is happening "
           "now, the second whether it is habitual. Both are sorts and hashes "
           "that exceeded work_mem. A single runaway "
           "statement can fill a volume in minutes, and every byte returns the "
           "moment it ends -- so currentActivity for what is running now is both "
           "the diagnosis and the fix. If this is the cause, the incident is "
           "over as soon as that statement is, and the follow-up is work_mem "
           "rather than storage.\n"
           "3. Bloat: space the tables hold and are not using. "
           "bloat-and-vacuum-review is the full investigation and tableBloat "
           "measures one table.\n"
           "   THE TRAP HERE IS THE OBVIOUS FIX. VACUUM FULL rewrites the table "
           "and needs free space equal to the table plus its indexes before it "
           "releases any -- on a disk that is already full it fails, and it "
           "holds an AccessExclusiveLock for the whole attempt. Ordinary VACUUM "
           "mostly does not return space to the filesystem either -- it makes it "
           "reusable inside the file. The exception is worth knowing on a full "
           "disk: VACUUM truncates empty pages at the END of a table and does "
           "give those back, so a table whose rows were deleted from the tail, "
           "or one that was bulk-loaded and then largely emptied, can return "
           "real space for the cost of an ordinary vacuum. Check whether the "
           "table has vacuum_truncate disabled in reloptions before promising "
           "it. Anywhere else in the file the space stays put, so bloat is "
           "usually not the thing to act on during the incident, and saying that "
           "plainly is more useful than proposing it.\n"
           "   If a database grew and no table in it did, call largeObjects. "
           "Large objects live in a catalog rather than in any user relation, "
           "so every size tool here is blind to them while diskUsage.databases "
           "counts their bytes -- that combination is the whole signature. It "
           "reports a count and owners and deliberately no sizes, because the "
           "bytes live in pg_largeobject which is not publicly readable. Do "
           "not propose lo_unlink from a count: an object is unreferenced only "
           "if no column holds its oid, which the catalog cannot tell you, and "
           "unlinking a live one loses data.\n"
           "4. Genuine growth. diskUsage.databases already ranked every database "
           "in the cluster, which matters because the one filling the disk is "
           "frequently not the one anybody is connected to. Within the database "
           "that stands out, listTableSizes ranks a schema. Do not forget the "
           "log directory, which diskUsage also sized: a stuck rotation fills a "
           "volume with nobody looking at it.\n"
           "5. Rank what can be freed by how reversible it is, and say the cost "
           "of each rather than only the size.\n"
           "   - Ending a statement that is spilling temp files: immediate, and "
           "costs that one statement.\n"
           "   - Raising or setting max_slot_wal_keep_size: bounds future growth, "
           "frees nothing now.\n"
           "   - Dropping a replication slot: frees the most, immediately, and is "
           "IRREVERSIBLE for its consumer -- a replica or subscriber behind that "
           "slot must be rebuilt from scratch. Say exactly what would have to be "
           "rebuilt, and prefer fixing or decommissioning the consumer. "
           "replication-slot-review establishes whether the consumer is stuck "
           "but alive or actually gone, and those two deserve opposite "
           "decisions.\n"
           "   - VACUUM FULL or a table rewrite: needs space you do not have, "
           "and locks. Not an incident action.\n"
           "   - More storage: buys time and fixes nothing, which is sometimes "
           "exactly the right call at three in the morning. Say so when it is.\n"
           "6. Report what is consuming the space, how fast it is growing, how "
           "long there is at that rate, and the one action that buys the most "
           "time for the least damage. Then say what the permanent fix is, "
           "because it is usually not the same thing.";
       }},

      {"buffer-cache-review",
       "See what is occupying shared buffers and whether it is the right thing.",
       {{"connection", "connection to review; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Review shared buffer usage" + on + ".\n\n"
           "0. Call checkPrivileges. Both buffer-cache tools need the monitoring "
           "role, and they are the whole of this review.\n"
           "1. Call bufferCacheSummary first. It is cheap; bufferCacheContents "
           "aggregates every buffer and is not.\n"
           "   Read the usage_counts histogram and usagecount_avg, not only the "
           "used and dirty totals. A cache that is full but sitting at low usage "
           "counts is being churned -- buffers are evicted before anything reads "
           "them twice -- and a cache that is full at high usage counts is simply "
           "working. Those two want opposite actions and buffers_used alone cannot "
           "tell them apart, which is the question step 5 has to answer.\n"
           "2. Call hostCapacity and compare shared_buffers against the host's "
           "RAM, and effective_cache_size against what the OS can plausibly "
           "cache.\n"
           "3. Call tableIOStats. A low hit ratio on a small, frequently read "
           "table is the actionable case; a low ratio on a large table scanned "
           "once a day is not a problem.\n"
           "   Then call ioStats for the same period. evictions counts buffers "
           "thrown out to make room and reuses counts a ring buffer recycling its "
           "own, which is what a large sequential scan does deliberately so it "
           "cannot flush the cache. Distinguishing them is the difference between "
           "a cache under real pressure and one doing its job: rising evictions is "
           "the finding, rising reuses is a big scan behaving correctly.\n"
           "4. Only if the summary suggests something is wrong, call "
           "bufferCacheContents to see which relations hold the buffers.\n"
           "5. Report whether the cache is undersized, mis-sized relative to "
           "the host, or being churned by one workload, and say which reading "
           "supports the conclusion.";
       }},

      {"capacity-check",
       "Check memory and parallelism settings against the machine.",
       {{"connection", "connection to check; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " for connection " + c;
         return
           "Check server capacity settings" + on + ".\n\n"
           "1. Call hostCapacity. If it reports that host RAM and vCPU count "
           "are unknown, say so and stop with a partial answer: PostgreSQL "
           "cannot see the machine it runs on, and those values have to be "
           "declared per connection in the config file. Do not guess them.\n"
           "2. Read derived.committed_worst_case_percent_of_ram. This is "
           "work_mem times max_connections plus maintenance_work_mem times "
           "autovacuum_max_workers, and it is the number that decides whether "
           "the OOM killer is a risk.\n"
           "   Read overrides beside it before believing any memory figure. "
           "settings is what pg_settings reports for THIS session, so an "
           "ALTER ROLE ... SET work_mem made for the application role is not in "
           "it -- and that is the role with the connections. The worst case "
           "already uses the largest work_mem any role carries, and "
           "work_mem_is_overridden says whether that differs from the session "
           "value you can see. An override here also explains a statement that "
           "is slow only from the application, and a statement_timeout or "
           "search_path set per role explains a good deal more, so read the "
           "whole list rather than only the memory entries.\n"
           "3. Compare shared_buffers and effective_cache_size against RAM.\n"
           "4. Check parallelism: max_parallel_workers_per_vcpu above 1 means "
           "a single query can oversubscribe the machine. That is the setting; "
           "triage-active-sessions is where the consequence is observed, and it "
           "collapses parallel workers into their leaders so the concurrency is "
           "counted in queries rather than in backends.\n"
           "5. Call databaseStats and read numbackends against max_connections "
           "to see how much of the worst case is actually reached. Read "
           "temp_files and temp_bytes on the same call: everything above is the "
           "worst case arithmetic, and these two are the only evidence of what "
           "actually happened. Temporary files are sorts and hashes that did not "
           "fit in work_mem and went to disk, so a large temp_bytes is work_mem "
           "being too small in practice however comfortable step 2 looked -- and "
           "a temp_bytes of zero is the argument against raising it. The two "
           "readings pull in opposite directions and the answer needs both.\n"
           "   sessions_abandoned, sessions_fatal and sessions_killed say whether "
           "connections are churning. Sizing max_connections against a count that "
           "is high because sessions keep dying is sizing for the symptom.\n"
           "6. Report each finding with the reading behind it, and name the "
           "setting to change.";
       }},

      {"replication-slot-review",
       "Find what a replication slot is holding back, and what it costs to release it.",
       {{"connection", "connection to review; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string c = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Review replication slots" + on + " and what they are holding back.\n\n"
           "An unconsumed slot is the failure mode that presents as something "
           "else. It holds back the xmin horizon, so vacuum cannot remove dead "
           "tuples anywhere in the cluster; and it pins WAL until the disk "
           "fills. Both symptoms get diagnosed as bloat, or as a disk problem, "
           "and neither diagnosis leads anywhere.\n\n"
           "0. Call checkPrivileges: a role without stats access sees less of "
           "replicationSlots and of currentActivity than this review needs. "
           "pg_stat_replication is restricted PER ROW rather than refused, so "
           "without it replicationStats shows the senders existing with their "
           "columns null -- which reads like an idle replica and is a "
           "permission answer.\n"
           "0a. Call replicationStats. A slot says what is RETAINED, in bytes; "
           "this says how far behind the consumer is, in seconds, and the two "
           "answer different questions. A slot with large retained_wal_bytes "
           "and a small replay_lag is a consumer that is keeping up through a "
           "burst; the same bytes with a growing replay_lag is one that is "
           "not, and only the second is a problem you can fix by making the "
           "consumer faster. Read the lag as documented: it reverts to NULL a "
           "short time after a standby has entirely caught up and WAL activity "
           "stops, so null on an idle replica means caught up, and a non-null "
           "value there is the last measurement rather than the current "
           "state.\n"
           "1. Call replicationSlots. For each slot read whether it is active, how "
           "far its restart_lsn trails the current WAL position, and its "
           "wal_status, which is a progression rather than a severity. reserved "
           "means the WAL it needs is within max_wal_size. extended means past "
           "max_wal_size but still retained -- by this slot OR by wal_keep_size, "
           "so check that setting before concluding the slot is the retainer. "
           "unreserved means the server has stopped retaining for it: some of "
           "the WAL it needs is due to be removed at the next checkpoint, which "
           "is what max_slot_wal_keep_size does when it is set. That is the last "
           "warning before the slot is unusable, and it is still reversible -- a "
           "consumer that catches up returns the slot to reserved or extended. "
           "lost means the WAL is already gone and the consumer cannot resume; "
           "that slot is dead and only rebuilding its consumer fixes it.\n"
           "   safe_wal_size is the budget between here and lost: bytes that can "
           "still be written before this slot is in danger. Read it rather than "
           "estimating from retained_wal_bytes and a WAL rate. Null means "
           "max_slot_wal_keep_size is -1 and nothing bounds the retention at "
           "all, which is a different and worse answer than a large number.\n"
           "   Three more fields answer questions you would otherwise estimate. "
           "inactive_since dates the problem, which beats inferring it from WAL "
           "volume: a slot inactive for an hour and one inactive since a deploy "
           "three weeks ago are different findings with the same "
           "retained_wal_bytes. One caveat that matters in exactly the case you "
           "care about: once a slot becomes invalid this value is never updated "
           "again, so on an invalidated slot it dates the invalidation and not "
           "the problem. Read it against invalidation_reason rather than alone. "
           "conflicting and invalidation_reason say the server retired the slot "
           "itself rather than it merely falling behind, and they do not cover "
           "the same slots: conflicting is always null for a physical slot, "
           "while invalidation_reason is set for both kinds -- so on a physical "
           "slot invalidation_reason is the only one of the two that answers. "
           "wal_removed, rows_removed, wal_level_insufficient and "
           "idle_timeout are each a different cause and a different fix, and "
           "none of them is repaired by giving the consumer more time. And for "
           "a logical slot the spill and stream counters say whether decoding "
           "is fitting in memory: heavy spill_txns and spill_bytes mean large "
           "transactions are being written to disk before they are sent, which "
           "is a logical_decoding_work_mem finding rather than a slow "
           "consumer.\n"
           "2. An inactive slot with growing lag is the finding. Before "
           "anything else, establish whose it is: listTopology and "
           "verifyTopology for physical replicas, listSubscriptions and "
           "listPublications for logical ones. A slot with no owner anybody "
           "recognises is the common case and the easy one. If the owner is a "
           "subscriber you can reach, call subscriptionStats on THAT connection "
           "-- not this one -- to separate a subscriber that is stuck from one "
           "that is merely gone: a stuck apply worker shows an error count or a "
           "table still copying, while a decommissioned one shows nothing at "
           "all and the slot is simply abandoned.\n"
           "3. Measure how fast it grows before deciding how urgent it is. "
           "checkpointStats reports WAL volume, and serverSettings carries "
           "max_slot_wal_keep_size -- if that is set, PostgreSQL will "
           "invalidate the slot rather than fill the disk, which trades a "
           "broken replica for a live primary. If it is unset, nothing bounds "
           "the growth.\n"
           "4. Call wraparoundStatus. The same held xmin horizon also stops "
           "freezing, and if wraparound headroom is shrinking that outranks the "
           "disk: one ends in a slow server, the other in a cluster that stops "
           "accepting writes.\n"
           "5. Report the slot, its owner, what it is holding, and how long the "
           "disk has at the current rate. Dropping a slot is irreversible for "
           "its consumer: say exactly what would have to be rebuilt, and prefer "
           "fixing or decommissioning the consumer over dropping the slot "
           "underneath it.";
       }},

      {"plan-schema-change",
       "Choose how to apply a DDL change by measuring the table it targets.",
       {{"change", "the change you intend to make, in your own words", true},
        {"schema", "schema of the table being changed", false},
        {"table", "table being changed", false}},
       [](const json& a) -> std::string {
         const std::string change = arg_or(a, "change", "");
         const std::string sch = arg_or(a, "schema", "");
         const std::string tbl = arg_or(a, "table", "");
         std::string target;
         if (!tbl.empty()) target = "Target: " + (sch.empty() ? "" : sch + ".") + tbl + "\n";
         return
           "Plan this schema change against what this database actually is.\n\n"
           "The change: " + change + "\n" + target + "\n"
           "This server is read-only and will run none of it. What you produce "
           "is a plan for an operator to apply.\n\n"
           "Do not answer from a recipe. The safe method for a change is a "
           "property of the table in front of you, not of the statement: the "
           "same DDL that is instant on one table is an outage on another. A "
           "table with no rows can be rewritten in place and nobody notices; "
           "the same rewrite at a billion rows is hours under an exclusive "
           "lock. Partitioning is the extreme case -- trivial before there is "
           "data, a migration project with a cutover after it. Reaching for the "
           "safest-at-scale approach on a small table is complexity nobody "
           "needs, and reaching for the simple one on a large table is the "
           "outage. Measure first, then choose, and say which reading decided "
           "it.\n\n"
           "1. Call checkPrivileges. tableStats and tableSize are what this "
           "whole plan rests on; if either is degraded here, say so rather than "
           "estimating, because they are what separates a metadata change from "
           "a full rewrite.\n"
           "2. Identify every object the change touches, then measure each of "
           "them -- not only the one named as the target. A statement that "
           "names one table routinely locks more than one: a foreign key locks "
           "the table it references as well as the table it is added to, a "
           "partitioned table means the parent and every partition, and a "
           "column that other tables reference cannot be considered alone. The "
           "object you did not name is often the busier one, and its lock is "
           "the one that surprises people. Read the change itself for the "
           "objects it names, and tableDetails for the ones the catalog knows "
           "about -- foreign keys in both directions, and inheritance or "
           "partition parents.\n"
           "   For each of them:\n"
           "   - tableStats: the row count, and n_distinct and most_common_vals "
           "when the change involves a default, an index or a partition key -- "
           "most_common_vals is the empirical answer to what value the rows "
           "already hold, and histogram_bounds low, mid and high are the "
           "observed extremes, which is the range a new constraint or default "
           "has to be true across\n"
           "   - columnHistogram on the partition key, if this is a "
           "partitioning change. Choosing boundaries without the distribution is "
           "guessing, and the guess is usually uniform when the data is not: a "
           "table partitioned by month is a table with one enormous partition "
           "wherever the traffic actually was. The bounds are equal-frequency, "
           "so every consecutive pair delimits roughly the same number of rows, "
           "and taking every Nth bound gives boundaries that divide the existing "
           "data evenly. Say which bounds you used, because that is what makes "
           "the choice checkable later against how the data has moved since\n"
           "   - tableSize: what a rewrite would actually move. Use the "
           "measured size, not the estimate; this is the number that turns "
           "\"instant\" into \"an hour\"\n"
           "   - tableDetails: the indexes, constraints, inbound foreign keys "
           "and triggers already there, and whether it is already partitioned. "
           "Each one multiplies the cost of a rewrite, and some rule out "
           "approaches outright\n"
           "   - the scan and tuple counters in tableStats: how busy it is. A "
           "lock window costs nothing on a table nothing is touching\n"
           "   - currentActivity and currentLocks: the oldest running "
           "transaction, and whether anything already holds or waits for a lock "
           "on any of these objects. A brief exclusive lock request waits "
           "behind a long transaction, and everything arriving after it waits "
           "behind that -- which is how a millisecond operation becomes an "
           "outage. Check this for every object the change touches, since one "
           "busy parent is enough to stall the whole statement\n"
           "   - serverSettings for the server version, since what is possible "
           "and what it costs both moved across majors\n"
           "   - listTopology and replicationSlots if the change rewrites: the "
           "WAL a rewrite generates has to reach every replica and pass through "
           "every slot\n"
           "   - listPublications, always. Logical replication does not carry "
           "DDL: if the table is published, this statement changes the publisher "
           "and nothing else, and the subscriber keeps the old shape until "
           "someone changes it too. The failure is silent until the next row "
           "arrives and apply stops. Two things decide the plan -- whether the "
           "table is published at all, and whether the change touches the "
           "primary key or the unique index serving as REPLICA IDENTITY, "
           "because a published table without one cannot replicate UPDATE or "
           "DELETE at all\n"
           "3. From those numbers, classify the change before writing any DDL. "
           "Say which of the three it is -- metadata only, a scan without a "
           "rewrite, or a full rewrite of the table and its indexes -- and "
           "separately what lock it needs and for how long. The lock level "
           "alone settles nothing: a strong lock held for a millisecond is "
           "safe, and a weak one held for an hour may not be. Duration is the "
           "number that matters, and duration comes from the measurements.\n"
           "4. Choose the method by matching that cost against what this table "
           "can tolerate. Above some size the incremental approach is the only "
           "one available; below it, it is machinery for nothing. State the "
           "size or rate at which your answer would flip, so the reasoning can "
           "be checked against a different table later.\n"
           "5. Give the plan as ordered DDL. Against each statement say the "
           "lock it takes, whether it rewrites, what must not be running "
           "alongside it, and roughly how long at this table's measured size.\n"
           "   If the table is published, the plan has two sides and the order "
           "between them is part of it: additive changes go on the subscriber "
           "first, so it can accept a row that already carries the new column; "
           "destructive ones go on the publisher first, so it stops sending "
           "what the subscriber is about to lose. Getting that backwards stops "
           "apply rather than degrading it. Say which side each statement runs "
           "on, and end with subscriptionStats on the subscriber as the check "
           "that apply survived -- a zero apply_error_count after the change is "
           "the only evidence that it did.\n"
           "6. Say what the revert looks like, and flag anything irreversible "
           "as irreversible whatever the size.";
       }},

      {"check-role-access",
       "Work out whether a role can use a table, view, function or procedure, and which rows.",
       {{"role", "the role to check; not necessarily the role this server connects as", true},
        {"object", "schema-qualified object name, e.g. billing.invoices", true},
        {"privilege", "SELECT, INSERT, UPDATE, DELETE or EXECUTE; omit to cover all of them", false},
        {"connection", "connection to check; defaults to the configured default", false}},
       [](const json& a) -> std::string {
         const std::string role = arg_or(a, "role", "");
         const std::string obj  = arg_or(a, "object", "");
         const std::string priv = arg_or(a, "privilege", "");
         const std::string c    = arg_or(a, "connection", "");
         const std::string on = c.empty() ? std::string() : " on connection " + c;
         return
           "Determine whether " + role + " can use " + obj + on +
           (priv.empty() ? ", for every privilege that applies to it"
                         : ", specifically " + priv) + ".\n\n"
           "Access is a chain of gates, not a grant. Every one has to pass, and "
           "the first that fails is the whole answer -- so find that one and "
           "name it, rather than reporting the object ACL and stopping. The "
           "usual wrong answer comes from checking the table and forgetting the "
           "schema.\n\n"
           "Two questions hide inside the one being asked, and they have "
           "different answers: whether the role may REACH the object at all, "
           "and WHICH ROWS it then sees. Grants settle the first. Row-level "
           "security settles the second and can reduce a complete set of grants "
           "to nothing without touching them. Answer both explicitly.\n\n"
           "0. Call checkRoleAccess with grantee " + role + ", the schema and "
           "the object. It answers the grant question outright, the way "
           "PostgreSQL answers it: has_table_privilege and its relatives fold in "
           "inheritance, grants to PUBLIC, ownership and superuser exactly as the "
           "server does. Everything below interprets that answer rather than "
           "recomputing it -- do not add up ACLs by hand when the server has "
           "already been asked.\n"
           "   Read four parts of it before anything else. privileges is the "
           "verdict per privilege. schema_access.usage is a separate gate and a "
           "false there beats a true above it. columns lists a partial grant "
           "where the table-level answer was no. row_level_security is a "
           "different question entirely and step 4 is where it is read.\n"
           "1. Call listRoles and establish what " + role + " IS before asking "
           "what it has. Three attributes can end the investigation here:\n"
           "   - superuser bypasses every check below, including row-level "
           "security. The answer is yes to everything; say so and stop rather "
           "than tracing grants that do not matter.\n"
           "   - bypass_rls means step 4 does not apply to this role, however "
           "the policies read.\n"
           "   - inherit explains a no that step 0 already reported. The has_* "
           "functions honour rolinherit, so a NOINHERIT member of a granted "
           "group comes back false rather than true -- the privilege is real and "
           "one SET ROLE away, and application code almost never issues one. "
           "Read it together with member_of to tell \"never granted\" from "
           "\"granted, unreachable as the application connects\", because those "
           "look identical in the verdict and need different fixes.\n"
           "   Then walk member_of transitively: a grant to any role in the "
           "closure counts, subject to inherit. Say which role in the chain "
           "actually carries the grant, because that is where an operator has "
           "to go to change it.\n"
           "2. Where checkRoleAccess said no, walk the gates to find WHICH one "
           "said it -- the tool gives the verdict, and this is how you turn a "
           "verdict into something an operator can act on. Where it said yes, "
           "read the same list to say what the yes does not cover.\n"
           "   a. CONNECT on the database, and whether the role can log in at "
           "all -- a group role with every grant in the cluster still cannot "
           "open a session.\n"
           "   b. USAGE on the schema, which step 0 returned as "
           "schema_access.usage. This is the gate that is missed most often: "
           "SELECT on the table is inert without it, and the error names "
           "permission on the TABLE, which sends people to the wrong object. Go "
           "to listSchemas only for what the tool does not carry -- who else "
           "holds USAGE, and whether PUBLIC does -- which is what says whether "
           "granting it is a one-role change or a decision about the schema.\n"
           "   c. The object\'s own privileges, from tableDetails or "
           "functionDetails. PUBLIC is a grantee like any other and applies to "
           "every role, so a grant to PUBLIC answers the question on its own -- "
           "and EXECUTE is granted to PUBLIC by default on every new function, "
           "which surprises people who never granted anything.\n"
           "   d. Ownership. The owner holds every privilege implicitly and "
           "need not appear in the grants map at all, so an empty map is not an "
           "empty answer.\n"
           "   e. Column-level grants, where the columns list carries them. "
           "SELECT on three of ten columns is a real yes that fails the moment "
           "a query names the fourth, so report it as the partial it is.\n"
           "3. If the object is a VIEW, the privileges checked are the view\'s "
           "own, and the base tables are read as the VIEW OWNER. So a role can "
           "hold SELECT on a view while holding nothing at all on what it "
           "selects from, and that is normal rather than a misconfiguration. "
           "Check reloptions for security_invoker: on PostgreSQL 15 and later a "
           "view can be defined to run as the caller instead, which flips this "
           "entirely -- base-table grants and base-table policies both come "
           "back into play. Say which of the two you are looking at.\n"
           "3b. Two questions this prompt cannot close, each with its own tool. "
           "defaultPrivileges says what the NEXT object of each type will "
           "grant: everything above answers about the objects that exist, and "
           "a correct answer today that is wrong for tomorrow's table is the "
           "standing cause of \"the new table is not readable and every old "
           "one is\" -- which presents as a broken grant and is a missing "
           "default. Note that a default applies only to objects created by "
           "the granting role, so read granted_by beside it. And "
           "roleDependencies answers the inverse of this whole prompt: what "
           "the role OWNS, cluster-wide, which is what blocks DROP ROLE and "
           "what an offboarding has to reassign.\n"
           "4. Now row-level security, and only for a table or a view over one. "
           "Step 0 returned the row_level_security block: if enabled is false, "
           "the grants above are the complete answer and this step is over. If "
           "it is true, everything above answers only whether the role may reach "
           "the table.\n"
           "   Read applies_to_role before the policies. It is the one thing no "
           "grants map can tell you, because it folds together three exemptions "
           "-- superuser, BYPASSRLS, and ownership without FORCE -- and a role "
           "that is exempt makes every policy below irrelevant. Each policy "
           "carries its own applies_to_role for the same reason: a policy that "
           "does not name this role, directly or through a role it belongs to, "
           "is not part of the answer however it reads.\n"
           "   - The OWNER BYPASSES RLS unless forced is also true. This is the "
           "single most common wrong test: someone checks as the owner, sees "
           "every row, and concludes the policies are permissive. FORCE ROW "
           "LEVEL SECURITY is what makes the owner subject to them, and without "
           "it the owner\'s experience says nothing about anyone else\'s.\n"
           "   - Read the policies map. Each policy names a command and a set of "
           "roles, and a policy whose roles are PUBLIC applies to everybody. "
           "Only policies matching both " + role + " and the command in question "
           "are in play.\n"
           "   - RLS ENABLED WITH NO APPLICABLE PERMISSIVE POLICY IS DENY ALL. "
           "This is the state nobody can explain: every grant checks out, "
           "has_table_privilege would say yes, and the table returns zero rows. "
           "If you find it, that is the finding -- say it in those words.\n"
           "   - Permissive policies OR together and restrictive ones AND, so "
           "adding a restrictive policy can veto everything the permissive ones "
           "allow. Report the combination, not a list.\n"
           "   - using gates which rows can be read or affected; with_check "
           "gates which rows may be written. They are frequently different, and "
           "a role that can read a row it cannot write back is a normal and "
           "confusing result worth stating outright.\n"
           "5. For a FUNCTION or PROCEDURE the privilege is EXECUTE, and "
           "security_definer changes who the body runs as. Under a security "
           "definer function the caller borrows the owner\'s privileges for "
           "everything inside, so the caller\'s own grants on the tables it "
           "touches are irrelevant -- and EXECUTE on it is effectively a grant "
           "of whatever the body can do. Say so plainly when you find one: it is "
           "the intended mechanism for controlled escalation and also the way "
           "access is given by accident.\n"
           "6. Report the chain, not a verdict. Name the gate that decided, and "
           "if the answer is no, name the single grant that would change it. If "
           "the answer is yes, say what it does not include -- the columns "
           "outside the grant, the rows outside the policy, the write that the "
           "read does not imply.\n"
           "7. One thing checkRoleAccess cannot fold in, so say it when it "
           "applies: a false for a NOINHERIT member of a granted group means "
           "\'not right now\' rather than \'never\'. The has_* functions honour "
           "rolinherit, so the privilege is real and one SET ROLE away -- and "
           "application code almost never issues one, which is usually what "
           "makes the answer no in practice rather than in principle. The role "
           "block carries inherits and member_of precisely so the two can be "
           "told apart.";
       }},

      {"explain-and-fix",
       "Explain one statement, establish why it is slow, and propose a fix that is verified rather than guessed.",
       {{"sql", "the statement to explain", true},
        {"params", "JSON array of parameter values, if the statement is parameterised", false},
        {"schema", "schema of the main tables, if they are not on the search path", false}},
       [](const json& a) -> std::string {
         const std::string sql = arg_or(a, "sql", "");
         const std::string prm = arg_or(a, "params", "");
         return
           "Explain this statement and propose a fix.\n\n"
           "SQL:\n" + sql + "\n\n" +
           (prm.empty() ? std::string()
                        : "Parameters: " + prm + "\n\n") +
           "Establish what is actually slow before proposing anything. A plan is "
           "evidence, not a verdict: a statement can be slow with a perfect plan "
           "because the data is cold, the table is bloated, or it spent its time "
           "waiting rather than working. Say which of those it is.\n\n"
           "0. Call checkPrivileges. EXPLAIN needs SELECT on every table the "
           "statement touches, so a restricted role fails here rather than "
           "returning a worse plan, and evaluateIndex in step 7 needs hypopg.\n"
           "1. Call explainQuery with this sql" +
           (prm.empty() ? std::string() : " and these params") +
           ". Leave analyze false first: the plan alone usually shows the "
           "problem, and analyze really executes the statement.\n" +
           (prm.empty()
             ? std::string(
               "   This statement was given without parameters. If it carries $n "
               "placeholders it is planned with GENERIC_PLAN -- the plan "
               "PostgreSQL builds knowing nothing about the values, which is what "
               "a prepared statement gets once it settles on a generic plan. That "
               "is frequently the whole answer to \"fast when I run it by hand, "
               "slow from the application\": ask for the concrete values and run "
               "this again with them, then compare. A generic plan that differs "
               "from the plan for real values is the finding, and no index fixes "
               "it.\n")
             : std::string(
               "   Parameters were supplied, so this is planned with those real "
               "values rather than generically. Run it once WITHOUT them as well "
               "and compare: if the generic plan differs, the application may be "
               "getting that one instead, and the statement is only slow when "
               "prepared. Skewed columns are where the two diverge, and step 4 is "
               "where you check for that.\n")) +
           "   Read the generic and analyzed flags the tool returns rather than "
           "assuming which plan you got.\n"
           "   Then read the plan's Settings block, and treat it as a second "
           "thing that can make the whole answer wrong. It names the settings "
           "that differ from the built-in default IN THIS SESSION, and this "
           "session is not the one the statement runs in. work_mem alone "
           "changes the algorithm rather than the cost -- the same statement "
           "plans as a HashAggregate with a large one and as a Sort plus "
           "GroupAggregate with a small one -- so node types, Sort Method and "
           "anything that spilled are all read off the wrong plan when they "
           "disagree. Call hostCapacity and compare Settings against "
           "overrides, which carries the per-role and per-database values "
           "pg_settings cannot show. If the executing role has its own "
           "work_mem, say so and say that this plan is not the plan "
           "production gets, before drawing anything else from it.\n"
           "2. If the plan alone is not conclusive and the statement only reads, "
           "call again with analyze true AND a timeout_ms -- analyze is refused "
           "without one. It runs EXPLAIN (ANALYZE, BUFFERS) and is honoured only "
           "after the plan is proven free of any ModifyTable node, so a "
           "data-modifying statement can never be executed here. Say that you are "
           "about to run it.\n"
           "   For an INSERT, UPDATE, DELETE or MERGE this step is unavailable by "
           "design, so the estimates are all you get. Reason from them and say so, "
           "rather than presenting an estimate as a measurement.\n"
           "3. Read the numbers in this order, because they answer different "
           "questions and the first one that answers yours ends the search.\n"
           "   - Estimated against actual rows, per node. A ratio past roughly "
           "100x is the planner being misinformed, and no index built on a wrong "
           "estimate will be chosen.\n"
           "   - Buffers, which analyze returns. shared_hit is memory and "
           "shared_read is disk: a plan that looks fine but reads heavily from "
           "disk is a cold cache or a working set larger than shared_buffers, and "
           "that is a capacity answer rather than a query one. Large temp blocks "
           "are a sort or hash that exceeded work_mem.\n"
           "   - Heap Fetches on an Index Only Scan. Nonzero means the visibility "
           "map is stale and the scan is going to the heap anyway; the fix is "
           "vacuum, not an index.\n"
           "   - Time not accounted for by any node. If the nodes are fast and "
           "the statement is not, it waited -- for a lock, or for I/O. That is "
           "triage-lock-contention or the buffers above, and neither is fixed by "
           "rewriting the query.\n"
           "4. Ground the plan in what the tables actually are, before believing "
           "anything the plan implies. Call tableStats for each table involved.\n"
           "   - rows first. A sequential scan of a few thousand rows is the "
           "correct plan and needs no fix; proposing an index there is noise.\n"
           "   - last_analyze and last_autoanalyze beside n_mod_since_analyze: "
           "stale statistics explain more bad plans than missing indexes do, and "
           "the two timestamps say whether anything is analyzing this table at "
           "all.\n"
           "   - most_common_vals, n_distinct and histogram_bounds for any "
           "column in a predicate. This is the empirical answer to whether the "
           "column is skewed, and skew is what makes one plan right for a common "
           "value and wrong for a rare one -- the same thing that makes a generic "
           "plan dangerous.\n"
           "   Then use them, rather than only reading them. Both carry values "
           "that actually occur in the column, so they are usable directly as "
           "parameters: most_common_vals[0] is the most frequent value the table "
           "holds, and histogram_bounds low, mid and high are the observed "
           "minimum, median and maximum. Re-plan the statement with each in turn "
           "and compare. A plan that is identical across all of them is stable "
           "and the parameters are not the problem; a plan that flips between a "
           "common value and an extreme one is parameter-sensitive, and that is "
           "the finding -- an index chosen for one end of the distribution will "
           "be wrong at the other, and the generic plan is wrong for both.\n"
           "   This is the one test that needs no invention. A constant you made "
           "up may match no rows and produce a plan for a case that never "
           "happens; these values are what is actually there. Where "
           "histogram_bounds is null the column has no histogram at all -- every "
           "value is in the MCV list, or nothing has analyzed it -- and which of "
           "those it is comes from the analyze timestamps above.\n"
           "   Three points settle whether the plan is stable. When they are not "
           "enough -- the plan flips somewhere between them and you need to know "
           "where, or the estimate is wrong in a way the extremes do not explain "
           "-- call columnHistogram for that one column. It returns every bound, "
           "and they are equal-frequency, so consecutive entries bunched close "
           "together are a dense region of the distribution and a wide gap is a "
           "sparse one. Sampling across the buckets rather than at the ends is "
           "how you find where the plan actually turns.\n"
           "   If a scan reads far more heap than it returns rows and the "
           "statistics are current, suspect bloat: tableBloat measures the table "
           "and indexBloat one index, and bloat-and-vacuum-review is the fuller "
           "investigation.\n"
           "5. Classify the fix before writing one, and say which it is. Either "
           "the statement asks for something the planner cannot use -- a "
           "predicate that is not sargable, a function or cast over an indexed "
           "column, NOT IN against a nullable subquery, OFFSET deep into a large "
           "result -- and the fix is a rewrite. Or the planner was misinformed, "
           "and the fix is statistics: an ANALYZE, a higher statistics target, or "
           "extended statistics for correlated columns -- call "
           "listExtendedStatistics first, because an object that exists and is "
           "not helping is a different problem from one that was never created, "
           "and only the second is fixed by CREATE STATISTICS. There is a third "
           "state between those two: built false means the object was declared "
           "and never ANALYZEd, so it holds no data and changes no plan. That "
           "reads as a fix already in place and is really one never completed, "
           "and the answer to it is ANALYZE. built_kinds says which of the "
           "declared kinds were actually computed. Or the plan is "
           "right but under-resourced, and the fix is configuration such as "
           "work_mem for a node that spilled. Or nothing supports the access path "
           "the statement needs -- and only then is the fix DDL.\n"
           "   A fifth outcome is legitimate and often correct: the statement is "
           "already as fast as it can be, and the cost is inherent to the work it "
           "does. Say so plainly when it is true. Proposing a fix for a statement "
           "that does not need one is worse than proposing nothing.\n"
           "   Prefer them in that order, because that is the order of what they "
           "cost. An ANALYZE is free and instant. A rewrite costs a deploy and "
           "nothing in the database. Configuration changes the behaviour of every "
           "other query too. An index is a write cost paid by every INSERT and "
           "UPDATE for as long as it exists, to buy speed for one read pattern. "
           "Say why the cheaper options were rejected rather than passing over "
           "them.\n"
           "6. If the answer is an index, choose its shape deliberately and "
           "justify each part -- an index is not a single decision.\n"
           "   - Call duplicateIndexes first. An index that is a prefix of one "
           "that already exists buys nothing and costs writes forever, and this "
           "is the most common wasted proposal.\n"
           "   - Column order: equality predicates first, then the range or "
           "inequality, then anything used only for ordering. A composite index "
           "is usable only up to its first range column.\n"
           "   - INCLUDE for columns the statement returns but does not filter "
           "on, which is what buys an index-only scan without widening the key.\n"
           "   - A WHERE clause on the index itself when the statement always "
           "carries the same selective constant: a partial index is smaller and "
           "cheaper to maintain.\n"
           "   - The operator class where it is not the default -- text pattern "
           "matching, trigram search and jsonb containment each need one, and the "
           "index is simply not used without it.\n"
           "7. Verify what can be verified, here, before recommending it.\n"
           "   - A rewrite is fully checkable: call explainQuery on the rewritten "
           "statement and show that the plan changed, and how. Same params, so "
           "the comparison is honest.\n"
           "   - An index is checkable wherever hypopg is installed: call "
           "evaluateIndex with the CREATE INDEX statement and report whether the "
           "planner actually took it. A proposed index the planner ignores is the "
           "common case and a cost figure alone hides it. checkPrivileges says "
           "whether hypopg is there; where it is not, an index is a prediction "
           "and must be presented as one rather than as a result.\n"
           "   - Compare like with like. A lower cost estimate is not a result; "
           "what supports the claim is the node that disappeared, the row count "
           "that stopped being wrong, or the buffers that stopped being read.\n"
           "8. Report the chain: what the statement does, which reading showed "
           "the cause, the fix, and the evidence it works. State how anyone would "
           "confirm it afterwards -- for a statement that came from "
           "pg_stat_statements, mean_exec_time on the same queryid is the "
           "measurement, and it needs a reset or a before-figure to mean "
           "anything. Hand any DDL to plan-schema-change rather than giving a "
           "CREATE INDEX to run: whether an index is correct and whether it is "
           "safe to build on this table are different questions, and evaluateIndex "
           "answers only the first.";
       }},
    };
    return v;
  }
